# Not installed
# - fcoe-utils (x86_64 kernel doesn't support it)
# - NetworkManager (Azure Linux primarily uses systemd-networkd)

FROM mcr.microsoft.com/azurelinux-beta/base/core:4.0

# export
ARG TARGETARCH

RUN \
if [ "${TARGETARCH}" == "amd64" ]; then \
    dnf -y install --setopt=install_weak_deps=False \
        systemd-boot \
        systemd-ukify \
; fi

RUN dnf -y install --setopt=install_weak_deps=False \
    asciidoc \
    bash-completion \
    bluez \
    btrfs-progs \
    busybox \
    cargo \
    chrony \
    cifs-utils \
    crypto-policies-scripts \
    cryptsetup \
    device-mapper-multipath \
    dhcpcd \
    diffutils \
    dnsmasq \
    dracut-live \
    e2fsprogs \
    erofs-utils \
    fuse3 \
    gcc \
    ignition \
    iproute \
    iputils \
    iscsi-initiator-utils \
    jq \
    kbd \
    kdump-utils \
    kernel \
    kexec-tools \
    kmod-devel \
    libfido2 \
    libkcapi-hmaccalc \
    libselinux-utils \
    lvm2 \
    make \
    mdadm \
    memstrack \
    ndctl \
    nfs-utils \
    nvme-cli \
    openssl \
    parted \
    pcsc-lite \
    qemu \
    qemu-kvm \
    rng-tools \
    rsyslog \
    squashfs-tools \
    swtpm \
    systemd-container \
    systemd-devel \
    systemd-networkd \
    systemd-resolved \
    tar \
    tcpdump \
    tpm2-tools \
    xfsprogs \
    xorriso \
    && dnf -y update && dnf clean all
