FROM mcr.microsoft.com/azurelinux-beta/base/core:4.0

# export
ARG TARGETARCH

RUN \
if [ "${TARGETARCH}" == "amd64" ]; then \
    dnf -y install --setopt=install_weak_deps=False \
        systemd-boot \
        systemd-ukify \
; fi

RUN dnf -y install --setopt=install_weak_deps=False \
    asciidoc \
    bash-completion \
    bluez \
    btrfs-progs \
    cargo \
    chrony \
    cifs-utils \
    cryptsetup \
    dhcpcd \
    diffutils \
    dnsmasq \
    e2fsprogs \
    fuse3 \
    gcc \
    iproute \
    iputils \
    iscsi-initiator-utils \
    jq \
    kbd \
    kexec-tools \
    kernel \
    kmod-devel \
    libkcapi-hmaccalc \
    libselinux-utils \
    lvm2 \
    make \
    mdadm \
    ndctl \
    nfs-utils \
    nvme-cli \
    openssl \
    parted \
    pcsc-lite \
    qemu \
    qemu-kvm \
    rng-tools \
    rsyslog \
    squashfs-tools \
    swtpm \
    systemd-container \
    systemd-devel \
    systemd-networkd \
    systemd-resolved \
    tar \
    tcpdump \
    tpm2-tools \
    xfsprogs \
    xorriso \
    && dnf -y update && dnf clean all

# disable systemd-portabled - it is optional and allows to pass the CI
# disable multipath dracut module - it interferes with the CI on azurelinux
RUN \
    rm -rf /usr/bin/portablectl /usr/lib/systemd/systemd-portabled ;\
    echo 'omit_dracutmodules+=" multipath "' > /usr/lib/dracut/dracut.conf.d/02-dist.conf
