---
name: Container

on:  # yamllint disable-line rule:truthy
    schedule:
        - cron: '30 11 * * *'   # every day at 11:30 UTC
    push:
        branches: [main]
        paths:
            - 'test/container/**'
            - '.github/workflows/container.yml'
    pull_request:
        branches: [main]
        paths:
            - 'test/container/**'
            - '.github/workflows/container.yml'
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    packages: write
    contents: read

jobs:
    amd64:
        if: github.repository == 'dracut-ng/dracut-ng' || vars.CONTAINER == 'enabled'
        name: ${{ matrix.config.tag }} on ${{ matrix.config.platform }}
        runs-on: ubuntu-latest
        concurrency:
            group: amd64-${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.tag }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                config:
                    - {dockerfile: 'Dockerfile-debian', tag: 'debian:latest', platform: 'linux/amd64'}
                    - {dockerfile: 'Dockerfile-fedora', tag: 'fedora:latest', platform: 'linux/amd64'}
                    - {dockerfile: 'Dockerfile-opensuse', tag: 'opensuse:latest', platform: 'linux/amd64'}
                    - {dockerfile: 'Dockerfile-arch', tag: 'arch:latest', platform: 'linux/amd64'}
                    - {dockerfile: 'Dockerfile-debian', tag: 'ubuntu:latest', platform: 'linux/amd64'}
                    - {dockerfile: 'Dockerfile-alpine', tag: 'alpine:latest', platform: 'linux/amd64'}
                    - {dockerfile: 'Dockerfile-void', tag: 'void:latest', platform: 'linux/amd64'}
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up env
              run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
            - name: Build and Push Container
              uses: docker/build-push-action@v6
              with:
                  file: test/container/${{ matrix.config.dockerfile }}
                  tags: ghcr.io/${{env.repository_owner}}/${{ matrix.config.tag }}
                  push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
                  platforms: ${{ matrix.config.platform }}
