name: Integration Test  (extra)

on:
    schedule:
        -  cron: '30 23 * * *'   # every day at 23:30 UTC

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    basic:
        # run this test on all containers
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 10
        concurrency:
            group: basic-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container: [
                        "alpine:edge",
                        "centos:stream10-development",
                        "fedora:rawhide",
                        "debian:sid",
                        "ubuntu:rolling",
                ]
                test: [
                        "10",
                        "11",
                        "12",
                        "20",
                        "21",
                        "22",
                        "23",
                        "24",
                        "25",
                        "26",
                        "30",
                        "40",
                        "41",
                        "42",
                        "80",
                        "81",
                ]
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}
            options: '--device=/dev/kvm --privileged'
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: TARGETS='all install cleaninstall check' DRACUT=dracut ./test/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
