---
name: Integration Test

on:  # yamllint disable-line rule:truthy
    pull_request:
        branches: [main]
        paths-ignore:
            - antora-playbook.yaml
            - 'doc_site/**'
            - 'man/**'

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    # set V to 2 when re-running jobs with debug logging enabled
    # see https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging
    V: "${{ secrets.ACTIONS_STEP_DEBUG && '2' }}"

jobs:
    basic:
        # run this test on all containers
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 20
        concurrency:
            group: basic-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container:
                    - ubuntu
                test:
                    - "10"
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}:latest-amd
            options: '--device=/dev/kvm'
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v4
            - name: "${{ matrix.container }} TEST-${{ matrix.test }}"
              run: ./test/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}

    arm64:
        name: ${{ matrix.test }} on ${{ matrix.container }} on arm64
        runs-on: ubuntu-24.04-arm
        timeout-minutes: 20
        concurrency:
            group: arm64-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container:
                    - debian
                    - fedora
                    - void
                    - ubuntu
                test:
                    - "12"
                    - "10"
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}:latest-arm
            options: '--privileged'
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v4
            - name: "${{ matrix.container }} TEST-${{ matrix.test }}"
              run: ./test/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}

