name: "Labeler"

# runs on pull_request_target instead of pull_request
# see https://github.com/actions/labeler?tab=readme-ov-file#permissions
on:
    pull_request_target:

jobs:
    triage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@main
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
